---
title: "hwk4"
author: "blair christensen"
date: "2/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
#1
```{r}
x<-1.1
a<-2.2
b<-3.3
z<-x^(a^b)
#(a)
z
z<-(x^a)^b
#(b)
z
z<-3*(x^3)+2*(x^2)+1
#(c)
z
```
#2
```{r}
#a
a1<- seq(from=1, to=8,length=8)
a2<-rev(a)
a<-c(a1,a2[2:8])
a

#b
b1<-seq(5)
b<-rep(x=b1,times=b1)
b

#c
c1<-seq(5)
c<-rev(rep(c1,c1))
c
```
#3
```{r}
c2p <- function(x, y)
{
  r <- sqrt(x^2 + y^2)
  t <- atan(y/x)
  c(r,t)
}
x<-runif(1)
y<-runif(1)
c2p(x,y)
```
#4
```{r}
queue<-c("sheep","fox","owl","ant")
queue
#a
queue<-c(queue,"serpent")
queue
#b
#queue<-queue(which(V1!="sheep"))
queue<-queue[-which(queue=="sheep")]
queue
#c
queue<-c("donkey",queue)
queue
#d
queue<-queue[-which(queue=="serpent")]
queue
#e
queue<-queue[-which(queue=="owl")]
queue
#f
queue<-append(queue,"aphid",after=(which(queue == "ant")-1))
queue
#g
which(queue == "aphid")
```
#5
```{r}
a<-seq(1:100)
a<-a[-which((a[]%%2==0))]
a<-a[-which((a[]%%3==0))]
a<-a[-which((a[]%%7==0))]
a


```