---
title: "hwk6"
author: "blair christensen"
date: "2/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

4. 
```{r}
#simulate new dataset, normal distribution is best
library(ggplot2)
library(MASS)
z <- rnorm(n=41,mean=465483, sd=123153)
z <- data.frame(1:41,z)
names(z) <- list("ID","myVar")
z <- z[z$myVar>0,]
str(z)
summary(z$myVar)
p1 <- ggplot(data=z, aes(x=myVar, y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2) 
p1
p1 <-  p1 +  geom_density(linetype="dotted",size=0.75)
print(p1)
normPars <- fitdistr(z$myVar,"normal")
print(normPars)
str(normPars)
#max likelihood estimates
normPars$estimate["mean"] # note structure of getting a named attribute
meanML <- normPars$estimate["mean"]
sdML <- normPars$estimate["sd"]

xval <- seq(0,max(z$myVar),len=length(z$myVar))

stat <- stat_function(aes(x = xval, y = ..y..), fun = dnorm, colour="red", n = length(z$myVar), args = list(mean = meanML, sd = sdML))
p1 + stat
```

How do they compare?


