---
title: "hwk9"
author: "blair christensen"
date: "3/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#hwk9
#simulate data for 1st trial
simDataNaB<-function(mu1=.5,mu2=.35,mu3=.35, mu4=.35,sd1=.1,sd2=.1,sd3=.1, sd4=.1) {
  library(ggplot2)
  library(boot)
  library(partsm)
  library(tidyverse)
  t0x <- round(rnorm(500, mean = mu1, sd = sd1))
  propsurv<-sum(t0x)/500
  A = data.frame(id = 1:500,trt='0', t0x, propsurv)
  t0x <- round(rnorm(500, mean = mu2, sd = sd2))
  propsurv<-sum(t0x)/500
  B = data.frame(id=501:1000, trt='0.25',t0x, propsurv)
  t0x <- round(rnorm(500, mean = mu3, sd = sd3))
  propsurv<-sum(t0x)/500
  C = data.frame(id = 1001:1500,trt='1', t0x, propsurv)
  t0x <- round(rnorm(500, mean = mu4, sd = sd4))
  propmort<-sum(t0x)/500
  D = data.frame(id=1501:2000, trt='4',t0x, propsurv)
  NaB<-rbind(A,B,C,D)
  mutate(NaB,Mort=sum(t0x)/2000)
  return(NaB)
}
#simulate data for second trial 

simDataC<-function(mu1=.3,mu2=.6,mu3=.7,sd1=.2,sd2=.1,sd3=.1) {
  library(ggplot2)
  library(boot)
  library(partsm)
  library(tidyverse)
  t0x <- round(rnorm(500, mean = mu1, sd = sd1))
  propsurv<-sum(t0x)/500
  A = data.frame(id = 1:500,trt='0', t0x, propsurv)
  t0x <- round(rnorm(500, mean = mu2, sd = sd2))
  propsurv<-sum(t0x)/500
  B = data.frame(id=501:1000, trt='0.25',t0x,propsurv)
  t0x <- round(rnorm(500, mean = mu3, sd = sd3))
  propsurv<-sum(t0x)/500
  C = data.frame(id = 1001:1500,trt='1', t0x,propsurv)
  Cr<-rbind(A,B,C)
  return(Cr)
}
NaB<-simDataNaB()

Cr<-simDataC()
graphData<-function(data,x,y,fill){
  library(ggplot2)
  ggplot(data=data,aes(x=trt,y=t0x, fill=propsurv))+geom_bar(stat='identity')
  }
graphData(Cr,trt,t0x,propsurv)
graphData(NaB,trt,t0x,propsurv)
```

